version: '3.7'
services:
  my-db:
    image: postgres:16.1-alpine
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: travel_agency
    restart: unless-stopped

  my-app:
    build:
      context: ./Mindera-Travel-Agency
      dockerfile: Dockerfile
    container_name: travel-agency
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://my-db:5432/travel_agency
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8080:8080
    restart: on-failure
    links:
      - my-db

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0.36
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: flights
    restart: on-failure

  flight-app:
    build:
      context: ./Flight_Database
      dockerfile: Dockerfile
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysql-db:3306/flights
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=secret
    ports:
      - 8081:8081
    restart: on-failure
    depends_on:
      - mysql-db

  hotel-app:
    build:
      context: ./Quarkus_Hotel_Project
      dockerfile: Dockerfile.jvm
    environment:
      - QUARKUS_MONGODB_CONNECTION_STRING=mongodb://mongodb:27017
      - QUARKUS_MONGODB_DATABASE=hotels
    ports:
      - 9000:9000
    restart: on-failure
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017

volumes:
  data: